"""Initial migration

Revision ID: 43f3adce9b7f
Revises: 3ce8385932d0
Create Date: 2023-06-02 18:11:17.887969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f3adce9b7f'
down_revision = '3ce8385932d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
