"""Updated Product model

Revision ID: 920ea941891e
Revises: aa0372c621b9
Create Date: 2023-06-04 17:12:36.886994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920ea941891e'
down_revision = 'aa0372c621b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
