"""Create categories table

Revision ID: 9d7619994399
Revises: 7f01654a2f3c
Create Date: 2023-06-05 19:15:54.660595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7619994399'
down_revision = '7f01654a2f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
