"""Add quantity and category to Product

Revision ID: aa0372c621b9
Revises: 43f3adce9b7f
Create Date: 2023-06-04 14:22:05.370170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0372c621b9'
down_revision = '43f3adce9b7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
